version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - db
    environment:
      FRONTEND_URL: http://localhost:5173
      SECRET: mysecretpassword
      DATABASE_URL: postgresql://postgres:mysecretpassword@localhost:5432/mydatabase
    ports:
      - "3000:3000"
  
    command: sh -c bun run start

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: bun run dev
    depends_on:
      - backend

